name: mighty_plant_admin
description: A new Flutter application.

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

#  firebase crashlytics analytics support
  firebase_crashlytics: ^3.3.2
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  # Used for speed up the coding and font selection
  nb_utils: ^5.0.8
  google_fonts: ^5.0.0

  #  used for API calling and Showing Html data
  http: ^1.0.0
  intl: ^0.18.1
  crypto: ^3.0.3
  html: ^0.15.3
  flutter_html: ^2.2.1
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2

#  Used for Images and icon
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  flutter_vector_icons: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flutter_staggered_grid_view: ^0.6.2

#  Application information
  package_info: ^2.0.2

#  Used for chart
  syncfusion_flutter_charts: ^21.2.8

# Bottom NavigationBar
  convex_bottom_bar: ^3.2.0
  bottom_navy_bar: ^6.0.0

# State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# State Management Technique
  build_runner: ^2.4.4
  mobx_codegen: ^2.3.0
#flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.0
  webview_flutter: ^2.0.4
  ffi: ^2.0.1
  wakelock: ^0.6.2
  win32: ^3.0.0
  flutter_math_fork: ^0.7.1
  flutter_svg: ^1.0.0
  flutter_html: 2.2.1
  file: ^6.1.4
  platform: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flags/
    - lang/




