name: plant_flutter
description: A place to buy plants from anywhere in the world.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  onesignal_flutter: ^3.5.1
  wp_json_api: ^3.3.3

  # Firebase
  firebase_analytics: 10.4.3
  firebase_crashlytics: 3.3.3
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  google_sign_in: ^6.1.3
  the_apple_sign_in: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2

  nb_utils: ^5.0.8
  flutter_svg: ^2.0.6
  url_launcher: ^6.1.11
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^5.0.0
  flutter_staggered_animations: ^1.1.1
#  slide_to_act: ^2.0.1
  timeline_tile: ^2.0.0
  local_hero: ^0.2.0
  photo_view: ^0.14.0
  action_slider: ^0.6.1

  # Payment
  razorpay_flutter: ^1.3.5
  flutter_paystack: ^1.0.7

  html: ^0.15.3
  intl: ^0.18.1
  share_plus: ^7.0.2
  package_info_plus: ^4.0.2
  flutter_html: ^2.2.1

  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  image_picker: ^0.8.7+5
  webview_flutter: ^4.2.1

  # ADS
  #  google_mobile_ads: ^3.0.0
  google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter
      ref: 356875362ddb2ac2e0056385d2729c093722fb8d
      path: packages/google_mobile_ads

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  mobx_codegen: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.0
  webview_flutter: ^2.0.4
  ffi: ^2.0.1
  wakelock: ^0.6.2
  win32: ^3.0.0
  flutter_math_fork: ^0.7.1
  flutter_svg: ^1.0.0
  flutter_html: 2.2.1
#  slide_to_act: 2.0.1

flutter:

  uses-material-design: true

  assets:
    - asset/app/
    - asset/flag/
    - asset/icon/
    - asset/

